In [155]:
#importando bibliotecas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Obtenção dos Dados

Todos os dados que estão sendo utilizados aqui foram retirados a partir do site do [Kaggle](https://www.kaggle.com/greenwing1985/housepricing).

Vamos utilizar um dataset disponível no Kaggle que foi gerado por computador para treinamento de machine learning. 
Esse Conjunto de dados é um banco de dados de imóveis, onde possuiem algumas caracteristicas desses imóveis como: Área, quantidade de banheiros, preço do imóvel e muitas outras características.
Como esse conjunto de dados é destinado ao treinamento não será necessário a limpeza dos Outliers.

## Análise dos Dados

Logo abaixo irei disponibilizar uma breve explicação do que é cara uma das colunas do nosso conjunto de dados.

**Dicionário das variáveis**

* `Area` - Área do imóvel. 
* `Garage` - Número de vagas de garagem.
* `FirePlace` - Números de lareiras.
* `Baths` - Número de banheiros do imóvel.
* `White Marble` - Se o imóvel tem acabamento em mármore branco. 
* `Black Marble` - Se o imóvel tem acabamento em mármore preto.
* `Indian Marble` - Se o imóvel tem acabamento em mármore Indiano.
* `Floors` Se o imóvel tem mais de um andar (1) ou apenas um(0)
* `City` - Cidade que o imóvel se encontra. 
* `Solar` - Se possui energia Solar
* `Electric` - Se possui energia elétrica
* `Fiber` - Se o imóvel tem Fibra
* `Glass Doors` - Se o imovél possui portas de vidro(1) ou não (0).
* `Swiming Pool` - Se o imóvel tem piscina(1) ou não(0).
* `Garden` - Se o imóvel tem jardim(1) ou não(0).
* `Prices` - Preços do imóveis.

Vamos dar uma análisada nas 5 primeiras linhas do nosso conjunto de dados.

In [156]:
print("Vamos dar uma analisada nas 5 primeiras linhas do nosso onjunto de dados que iremos utilizar para nosso estudos.")
df = pd.read_csv(r"C:\Users\joaog\GitProjetos\DataScience_dados_projetos\HousePrices_HalfMil.csv", sep=",")
df.head()

Vamos dar uma analisada nas 5 primeiras linhas do nosso onjunto de dados que iremos utilizar para nosso estudos.

,Area,Garage,FirePlace,Baths,White Marble,Black Marble,Indian Marble,Floors,City,Solar,Electric,Fiber,Glass Doors,Swiming Pool,Garden,Prices
0,164,2,0,2,0,1,0,0,3,1,1,1,1,0,0,43800
1,84,2,0,4,0,0,1,1,2,0,0,0,1,1,1,37550
2,190,2,4,4,1,0,0,0,2,0,0,1,0,0,0,49500
3,75,2,4,4,0,0,1,1,1,1,1,1,1,1,1,50075
4,148,1,4,2,1,0,0,1,2,1,0,0,1,1,1,52400

In [157]:
print("A quantidade de linhas do nosso conjunto de dados é igual a:", df.shape[0])
print('A quantidade de colunas do nosso conjunto de dados é igual a:',df.shape[1])

A quantidade de linhas do nosso conjunto de dados é igual a: 500000
A quantidade de colunas do nosso conjunto de dados é igual a: 16

# Regressão Linear
` Definição`

"Dada uma coleção de dados amostrais emparelhados, a equação de regressão
$$\displaystyle \hat{y} = b_{0} + b_{1} x$$
descreve algebricamente a relação entre as duas variáveis $x$ e $y$. O Gráfico da 
equação da regressão é chamada de reta de regressão(ou reta do melhor ajuste, ou reta de mínimos quadrados.)</br>
Podemos perceber que o $y$ é uma variavel dependente do $x$, portando $y$ é denominado 
sendo nossa variavél dependente. Já o $x$ é a nossa váriavel explanátoria ou também chamada
de variável independente.
Essa primeira equação que foi demonstrada é referênte a uma equação de regressão
linear simples, podemos ter regressões lineares múltiplas, a formula abaixo é uma representação de uma equação multipla:
$$\displaystyle \hat{y} = b_{0} + b_{1} x_{1}+b_{2}x_{2} + ... + b_{k} x_{k}$$ 
Agora temos as váriavéis explatórias sendo $(x_{1}, x_{1},... ,x_{k})$ e continuamos tendo nossa váriavel dependente sendo $y$